
GRANT USAGE ON SCHEMA pg_catalog TO PUBLIC;
GRANT USAGE ON SCHEMA information_schema TO PUBLIC;
GRANT SELECT ON ALL TABLES IN SCHEMA pg_catalog TO public;
GRANT SELECT ON ALL TABLES IN SCHEMA information_schema TO public;

