SELECT current_database();
REVOKE ALL ON SCHEMA public FROM public; -- CREATE and USAGE
REVOKE ALL ON SCHEMA pg_catalog FROM public; -- CREATE and USAGE
REVOKE CREATE,USAGE ON SCHEMA information_schema FROM public; -- CREATE and USAGE
REVOKE ALL ON ALL TABLES IN SCHEMA pg_catalog FROM public;
REVOKE ALL ON ALL TABLES IN SCHEMA information_schema FROM public;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM public;

REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM public;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA pg_catalog FROM public;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA information_schema FROM public;

REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM public;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA pg_catalog FROM public;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA information_schema FROM public;

-- REVOKE ALL ON DOMAIN xyz FROM public;

REVOKE ALL PRIVILEGES ON SCHEMA pg_catalog FROM public;
